print("What is your name?")
x = input ()
print("How old are you?")
y = input ()
print("Where are you live?")
z = input ()
print("This is имя " + x)
print("It is возраст " + y)
print("(S)he live in " + z)
