Print ("What is your name?")
x = input ()
Print ("How old are you?")
y = input ()
Print ("Where are you live?")
z = input ()
Print ("This is имя" + x)
Print ("It is возраст" + y)
Print ("(S)he live in" + z)
